# -*- coding: utf-8 -*-
"""AnalyzeCatVSDog

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/......
"""

import cv2
import tensorflow as tf
import matplotlib.pyplot as plt

CATEGORIES = ['Dog', 'Cat']

def prepare(filepath):
  IMG_SIZE = 100
  img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
  new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
  plt.imshow(new_array, cmap='gray')
  plt.show()
  return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)

# Filepath of model
model = tf.keras.models.load_model('64x3-CNN-02Dropout.model')

# Filepath of image - 0 for Dog, 1 for Cat
prediction = model.predict([prepare('Filepath_Here.jpg')])
print(CATEGORIES[int(prediction[0][0])])

